export const ErrorCodes = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_OTP: "INVALID_OTP",
  INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
  UNAUTHORIZED: "UNAUTHORIZED",
  POST_NOT_FOUND: "POST_NOT_FOUND",
};
